### ISSUE TITLE
Nosetests has failure

### ISSUE THREAD

**Issue by GLMeece** [h3/python-libvin#4]
I am relatively new to using Nosetest, so perhaps I am not running this correctly. However, upon invoking `python setup.py test`, I get the following as a result consistently:

```python
running test
running egg_info
writing requirements to libvin.egg-info\requires.txt
writing libvin.egg-info\PKG-INFO
writing top-level names to libvin.egg-info\top_level.txt
writing dependency_links to libvin.egg-info\dependency_links.txt
reading manifest file 'libvin.egg-info\SOURCES.txt'
writing manifest file 'libvin.egg-info\SOURCES.txt'
running build_ext
tests.test_decoding.TestDecode.test_country ... ok
tests.test_decoding.TestDecode.test_is_pre_2010 ... FAIL
tests.test_decoding.TestDecode.test_is_valid ... ok
tests.test_decoding.TestDecode.test_less_than_500_per_year ... ok
tests.test_decoding.TestDecode.test_region ... ok
tests.test_decoding.TestDecode.test_vds ... ok
tests.test_decoding.TestDecode.test_vis ... ok
tests.test_decoding.TestDecode.test_vsn ... FAIL
tests.test_decoding.TestDecode.test_wmi ... ok
tests.test_decoding.TestDecode.test_year ... FAIL

======================================================================
FAIL: tests.test_decoding.TestDecode.test_is_pre_2010
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\gmeece\Documents\GitHub\libvin\tests\test_decoding.py", line 25
, in test_is_pre_2010
    assert_true(not v.is_pre_2010)
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
Testing: JM1BL1SF3A1267720
Testing: 2A4GM684X6R632476
Testing: 2B3KA43G27H825762
Testing: 1FAHP3FN8AW139719
Testing: 1GKEV13728J123735
Testing: 2FTCF15F2ECA55516

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.test_decoding.TestDecode.test_vsn
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\gmeece\Documents\GitHub\libvin\tests\test_decoding.py", line 55
, in test_vsn
    assert_equals(v.vsn, test['SEQUENTIAL_NUMBER'])
AssertionError: 'A55516' != '55516'
-------------------- >> begin captured stdout << ---------------------
Testing: JM1BL1SF3A1267720
Testing: 2A4GM684X6R632476
Testing: 2B3KA43G27H825762
Testing: 1FAHP3FN8AW139719
Testing: 1GKEV13728J123735
Testing: 2FTCF15F2ECA55516

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.test_decoding.TestDecode.test_year
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\gmeece\Documents\GitHub\libvin\tests\test_decoding.py", line 67
, in test_year
    assert_equals(v.year, test['YEAR'])
AssertionError: 1984 != 2014
-------------------- >> begin captured stdout << ---------------------
Testing: JM1BL1SF3A1267720 - 2010
Testing: 2A4GM684X6R632476 - 2006
Testing: 2B3KA43G27H825762 - 2007
Testing: 1FAHP3FN8AW139719 - 2010
Testing: 1GKEV13728J123735 - 2008
Testing: 2FTCF15F2ECA55516 - 1984

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 10 tests in 0.046s

FAILED (failures=3)
```

Q: Am I running these tests incorrectly, or is there an issue with the code/asserts?

**Comment by iamdavehawkins** [comment]
I believe you are running the tests correctly, as I'm getting the same results. 

It appears one VIN is causing all the problems (2FTCF15F2ECA55516) and there is an error in the "truth" data it is checking against. This is actually a model year 1984 vehicle, but in tests/__init__.py it's "truth" value is 2014, which is incorrect. Fixing this addresses two of the failing tests.

The other issue is not so simple. It appears the "truth" value for this VIN's sequential number is only 5 digits long. However, there is controversial information on the web. Wikipedia (among every other source I could find) suggest that the sequential number should be the last _six_ digits. However, when I follow the VIN decoder link (http://www.vindecoder.net/?vin=2FTCF15F2ECA55516&submit=Decode) it does in fact output only _five digits_ (55516) for the Sequence Number. This VIN is also odd because there is a character in the sequence number.

**Comment by GLMeece** [comment]
Thanks Dave! Making that date changed did indeed clean up those two failures.

Just for grins, I changed:
```json
'SEQUENTIAL_NUMBER': '55516'
```
to:
```json
'SEQUENTIAL_NUMBER': 'A55516'
```
...and the error goes away. However, as you mentioned, this is perhaps an iffy/edge case. Not sure what the _right_ thing to do is.  :grimacing:

**Comment by h3** [comment]
Merged ! Thanks guys
